# person:
#     lastName: zhangsan
#     age: 18
#     boss: false
#     birth: 2001/01/09
#     maps: {a1: 100,a2: 150}
#     lists: [lisi,zhaoliu]
#     dog:
#         name: 小狗
#         age: 2
# lastName: 123

